services:
  nickfood:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nickfood-app
    environment:
      DATABASE_URL: "file:./data/dev.db"
      NODE_ENV: production
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_URL: "https://nicolasfigueiredo.com/nickfood"
      AUTH_SECRET: "${AUTH_SECRET:-portfolio-demo-secret-key-2026}"
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    networks:
      - default
      - portfolio-net

volumes:
  app-data:

networks:
  default:
  portfolio-net:
    external: true
