import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBottomWrapper from "./components/navbottom-wrapper";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
// Remover imports de QueryClient, QueryClientProvider, useState
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import { useState } from "react";
import Providers from "./providers"; // Importar o novo componente Providers

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex justify-center md:w-full pb-20`}
      >
        <Providers> {/* Envolver com o novo componente Providers */}
          <SessionProvider session={session}>
            {children}
            <NavBottomWrapper />
            <Toaster richColors position="top-center" />
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
